on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrashghal.azurecr.io
        username: ${{ secrets.acr_acrashghal_username }}
        password: ${{ secrets.acr_acrashghal_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrashghal.azurecr.io/aksashghal:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrashghal.azurecr.io/aksashghal:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksashghal_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-ashghal | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-ashghal`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-ashghal
        container-registry-url: acrashghal.azurecr.io
        container-registry-username: ${{ secrets.acr_acrashghal_username }}
        container-registry-password: ${{ secrets.acr_acrashghal_password }}
        secret-name: aksashghaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-ashghal
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          acrashghal.azurecr.io/aksashghal:${{ github.sha }}
        imagepullsecrets: |
          aksashghaldockerauth
